"""道路グラフの前処理（投影済みメートル・メモリ内）。公開 API の再エクスポート。"""

from .defaults import (
    DEFAULT_CONNECT_OSM_NODE_IDS_ENABLED,
    DEFAULT_MERGE_DUPLICATE_ROADS_ENABLED,
    DEFAULT_PRUNE_CHAIN_ACCUM_ANGLE_DEG,
    DEFAULT_REMOVE_REDUNDANT_CHAIN_VERTICES_ENABLED,
    DEFAULT_ROAD_MERGE_ANCHOR_DELTA_M,
    DEFAULT_ROAD_MERGE_ANGLE_DEG,
    DEFAULT_ROAD_MERGE_DISTANCE_M,
    DEFAULT_ROAD_MERGE_MAX_ANCHOR_OFFSET_M,
    DEFAULT_ROAD_MERGE_MIN_OVERLAP_M,
    DEFAULT_ROAD_MERGE_MIN_OVERLAP_RATIO,
    DEFAULT_SNAP_ENDPOINTS_ENABLED,
    DEFAULT_SNAP_EPSILON_M,
    DEFAULT_SPLIT_INTERSECTIONS_ENABLED,
)
from .graph_model import InternalEdge, InternalNode, RoadGraph
from .pipeline import GraphPreprocessOptions, preprocess_road_graph

__all__ = [
    "DEFAULT_CONNECT_OSM_NODE_IDS_ENABLED",
    "DEFAULT_MERGE_DUPLICATE_ROADS_ENABLED",
    "DEFAULT_PRUNE_CHAIN_ACCUM_ANGLE_DEG",
    "DEFAULT_REMOVE_REDUNDANT_CHAIN_VERTICES_ENABLED",
    "DEFAULT_ROAD_MERGE_ANCHOR_DELTA_M",
    "DEFAULT_ROAD_MERGE_ANGLE_DEG",
    "DEFAULT_ROAD_MERGE_DISTANCE_M",
    "DEFAULT_ROAD_MERGE_MAX_ANCHOR_OFFSET_M",
    "DEFAULT_ROAD_MERGE_MIN_OVERLAP_M",
    "DEFAULT_ROAD_MERGE_MIN_OVERLAP_RATIO",
    "DEFAULT_SNAP_ENDPOINTS_ENABLED",
    "DEFAULT_SNAP_EPSILON_M",
    "DEFAULT_SPLIT_INTERSECTIONS_ENABLED",
    "GraphPreprocessOptions",
    "InternalEdge",
    "InternalNode",
    "RoadGraph",
    "preprocess_road_graph",
]
