"""
グラフ前処理の既定値（ブール・距離・角度）。

フロントの `frontend/src/debug/lib/graphPreview.ts` の `defaultGraphBuildOptions()` と、
バックエンドの `GraphPreprocessOptions` の既定フィールドと同一に保つこと。
"""

DEFAULT_CONNECT_OSM_NODE_IDS_ENABLED = True

DEFAULT_SNAP_ENDPOINTS_ENABLED = False
DEFAULT_SNAP_EPSILON_M = 3.0

DEFAULT_MERGE_DUPLICATE_ROADS_ENABLED = True
DEFAULT_ROAD_MERGE_DISTANCE_M = 20.0
DEFAULT_ROAD_MERGE_ANGLE_DEG = 22.0
DEFAULT_ROAD_MERGE_MIN_OVERLAP_M = 100.0
DEFAULT_ROAD_MERGE_MIN_OVERLAP_RATIO = 0.25
DEFAULT_ROAD_MERGE_ANCHOR_DELTA_M = 2.0
DEFAULT_ROAD_MERGE_MAX_ANCHOR_OFFSET_M = 0.0

DEFAULT_SPLIT_INTERSECTIONS_ENABLED = False

DEFAULT_REMOVE_REDUNDANT_CHAIN_VERTICES_ENABLED = True
DEFAULT_PRUNE_CHAIN_ACCUM_ANGLE_DEG = 10.0

# Overpass 応答の highway way 件数上限（メモリ・応答サイズの安全弁）
OVERPASS_MAX_WAYS: int = 50_000
